### ISSUE TITLE
Cannot clone submodules in the project

### ISSUE THREAD

**Issue by oliverzy** [kittykatattack/hexi#16]
Hi,

When I executed `git submodule update`, I got the following errors
`
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kittykatattack/bump.git' into submodule path 'src/modules/bump' failed`

The `git clone` & `git submodule init` commands are fine.

**Comment by kittykatattack** [comment]
Hmmm.. I'm not sure about this one.
Are there any experience Git users out there who could help?

**Comment by langft10** [comment]
@oliverzy The issue you are seeing is due to not being able to authenticate with GitHub using ssh. Typically this is due to not having an ssh key set up. If you did have one set up it is possible that it was deleted somehow, for instance through an OS upgrade. GitHub has a great guide that will walk you through checking if you have ssh keys and getting your ssh key set up here: 

https://help.github.com/articles/generating-an-ssh-key/
 
Hope that helps!

**Comment by icarito** [comment]
Hi!
For a casual user it's not necessary to setup ssh.
I've sent a pull request https://github.com/kittykatattack/hexi/pull/21 to make it easier for users who don't have ssh setup.
Hope it helps!
